### ISSUE TITLE
Use composer for autoload

### ISSUE THREAD

**Issue by turtle0x1** [goodot/fuzzy-dm#1]

**Comment by goodot** [comment]
I think it is done, is not it? It could be installed by composer . . .

**Comment by turtle0x1** [comment]
Not quite you still have an autoloader https://github.com/goodot/fuzzy-dm/blob/master/autoload.php when you could just use composers instead

**Comment by goodot** [comment]
could you please give me some example?

**Comment by turtle0x1** [comment]
In your composer.json you can do something like

```
    "autoload": {
        "psr-4": {
            "Some\\Namespace\\": "src/classes",
            "Some\\Other\\Namepsace": "src/lib"
        }
    },
```
